### ISSUE TITLE
Check for consistencies with capitalization of certain words.

### ISSUE THREAD

**Issue by grabear** [datasnakes/beri-isc-proposal#21]
Some words like Docker or Bioinformatics have upper and lower case forms in our proposal.  Find this and eradicate the problem

**Comment by sdhutchins** [comment]
Yupppp this is a big one. I think Docker should probably be capitalized. Unclear on Bioinformatics

**Comment by grabear** [comment]
I'm horrible about this.  I think I just like to see the way it looks, and then I just end up leaving it in different ways.

**Comment by grabear** [comment]
- `DataSnakes` 
- `Datasnakes` 
- `datasnakes` 
- `dataSnakes

**Comment by sdhutchins** [comment]
Bwahahah
