### ISSUE TITLE
Target Audience Discussion

### ISSUE THREAD

**Issue by grabear** [datasnakes/beri-isc-proposal#26]
Based on @scientificbruno's comments on the Google Doc:

> One of the things that I changed in my first batch of edits was to make the proposal more agnostic to the field. I made it more about data science in academia/heathcare instead of being unnecessarily specific with bioinformatics. I don’t see the benefit of being specific. We don’t want to exclude anyone for no reason.

My reply:
> I agree, but this also conflicts with our niche.  Do we risk saying data science as a whole? 

> Speculation:  I think data scientists in the financial sector largely have access to tools like Docker.  So they aren't necessarily going to use what we have.  Doesn't mean they won't.

> Observation:  We know bioinformaticist are interested in this.  Does this cross over to other disciplines in data science?  I think it probably does, but to what extent?

**Comment by grabear** [comment]
This is also relevant to #20

**Comment by scientificbruno** [comment]
The tool is relevant to all data scientists who can use the command line. We have seen interest among bioinformaticians because that's our community. These are not mutually exclusive statements.
